services:
  acheteteper:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_PATH: /data/database.db
      UPLOADS_PATH: /tmp/uploads
      DEBUG: false
    volumes:
      - ./data:/data
      - ./data/uploads:/tmp/uploads
      - ./:/app
    restart: unless-stopped

