server {
    listen 8000 default_server;

    root /app/src/public;
    index index.php index.html;

    access_log /dev/stdout;
    error_log /dev/stderr;

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    client_max_body_size 3M;
    fastcgi_buffers 64 4K;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass 127.0.0.1:9000;
    }

    location ~ /\.ht {
        deny all;
    }
}
