<!DOCTYPE html>
<html>

<head>
    <title><?= isset($title) ? \Httpeur\e($title) . ' - ' : '' ?>Httpeur Framework</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" type="image/png" href="/php-icon.png">
    <link rel="stylesheet" href="/app.css">
    <script src="/htmx.v2.0.8.min.js"></script>
</head>

<body hx-boost="true">
    <?php if (isset($extraStyles)): ?>
        <style>
            <?= $extraStyles ?>
        </style>
    <?php endif; ?>
    <div class="container">
        <?php if (isset($title)): ?>
            <h1><?= \Httpeur\e($title) ?></h1>
        <?php endif; ?>

        <?php require __DIR__ . '/_nav.phtml'; ?>

        <?= $content ?? '' ?>
    </div>
</body>

</html>