<h1>About Contact</h1>

<p>This is the about contact page.</p>

<style>
    .error {
        color: red;
    }

    .success {
        color: green;
    }
</style>

<div>
    <form action="/about/contact_submit" method="post">
        <input type="text" name="name" placeholder="Name" value="<?= $name; ?>">
        <input type="email" name="email" placeholder="Email" value="<?= $email; ?>">
        <input type="submit" value="Submit">
    </form>
    <?php if (isset($success)): ?>
        <p class="success">Contact submitted successfully</p>
    <?php endif; ?>
    <?php if (isset($errors['name'])): ?>
        <p class="error"><?= $errors['name']; ?></p>
    <?php endif; ?>
    <?php if (isset($errors['email'])): ?>
        <p class="error"><?= $errors['email']; ?></p>
    <?php endif; ?>
</div>